### ISSUE TITLE
Bug with Thaumcraft

### ISSUE THREAD

**Issue by LuxerIThink** [Tschipp/PrimitiveCrafting#1]
Hi. I found incompatibile between Thaumcraft and Primitive Crafting. Thaumcraft aspect icons are under primitive crafting block or items icons and It's look strange.
Screen I will send later.
Thanks for help

**Comment by Mike-U5** [comment]
You'll probably just have to change the keybind to something else besides shift.
Or use the Thaumcraft config settings that inverts shift-click behavior. (That's what I did)

**Comment by Tschipp** [comment]
This is fixed in next release (coming later today)
