### ISSUE TITLE
shift clicking to transfer items into an inventory caused a crash

### ISSUE THREAD

**Issue by majijn** [Tschipp/PrimitiveCrafting#12]
I was transferring some rustic ironwood logs into a IE crate and this crash happened 
[crash-2019-01-07_01.00.57-client.txt](https://github.com/Tschipp/PrimitiveCrafting/files/2731037/crash-2019-01-07_01.00.57-client.txt)

**Comment by majijn** [comment]
I forgot to mention I was holding the same type of log as I was transferring, but there isnt a recipe that uses two logs anyway.

**Comment by majijn** [comment]
just happened again, holding sticks, trying to transfer some misc vanilla flowers into an AA "small" crate this time. 
[crash-2019-01-09_18.13.37-client.txt](https://github.com/Tschipp/PrimitiveCrafting/files/2741881/crash-2019-01-09_18.13.37-client.txt)

**Comment by Tschipp** [comment]
Interesting... will take a look at it.

**Comment by Tschipp** [comment]
I tried everything you mentioned, I can't recreate it
