### ISSUE TITLE
[Bug] CraftTweaker removing recipes doesn't work with PrimitiveCrafting

### ISSUE THREAD

**Issue by UnlimatedStone9** [Tschipp/PrimitiveCrafting#16]
To put it simply I can remove a recipe using CraftTweaker however I can still craft it using PrimitiveCrafting, following this I'm going to assume that adding recipes will also result in them not being craftable using PrimitiveCrafting.

For example I removed this recipe but it's still craftable using your mod.
![image](https://user-images.githubusercontent.com/40124890/65049137-2fe16f80-d95d-11e9-89ba-2bdbea968f46.png)
![image](https://user-images.githubusercontent.com/40124890/65049143-34a62380-d95d-11e9-81ea-5a51b4d46b7a.png)
![image](https://user-images.githubusercontent.com/40124890/65049198-4687c680-d95d-11e9-82bd-64cebffdbb37.png)

**Comment by MasterEnderman** [comment]
there's a config option, so the mod doesn't register recipes on it's own. set it to false, so primitive crafting only uses the recipes you specified in your scripts. Furthermore there's a blacklist and whitelist to remove specific recipes.

**Comment by UnlimatedStone9** [comment]
I'll look into this further, thanks. While we're on the topic, the configuration option for blacklisting or whitelisting recipes wasn't very clear on what I was supposed to enter, I assume this is just the specific recipes name string?

**Comment by Tschipp** [comment]
Yes, this is true. When you remove a vanilla recipe you also need to remove the primitive recipe. This is not a bug. If you want to mass-remove recipes, I suggest making a function that calls both the vanilla recipe removal and the primitive recipe removal.
