### ISSUE TITLE
Discovered weird behavior when crafting with this mod

### ISSUE THREAD

**Issue by MasterEnderman** [Tschipp/PrimitiveCrafting#17]
I'm currently working on a modpack and one of my testers found a strange behavior when using your mod.

https://clips.twitch.tv/SassyNimbleCourgetteThunBeast

In this clip he tries to craft a "sharp bone" using a flint and a bone but when he initialized the crafting process it used the recipes with flint and wood logs to create a chest but insted of the logs it consumed the bones in his inventory.

https://clips.twitch.tv/HungryMoistBisonVoteNay

This clip is even stranger. He's supposed to craft a block which requires a "rock core" the item in the top left corner and the black ingots he clicked on the "rock core" but instead of the block that is specified in the recipe he got a "drying basin" which requires wooden logs and the black ingots. this time he wasn't even near the logs when he initialized the crafting process.

I hope you can fix this weird behavior. :)

**Comment by Tschipp** [comment]
That is very bizarre. I can see how the first could happen, just with some slight client/server desync. Not sure if that really is fixable.
For the second one, I saw that the recipe appeared for a split second while he was hovering the logs, meaning he was already holding shift. Then he probably clicked so fast, that it didn't reload the recipe and crafted it with the wood recipe instead. 
I think to be able to test this properly, I need to check out the pack myself. Can I download it anywhere?

**Comment by MasterEnderman** [comment]
It's not available yet, but I could send you a version via discord or something similar if you want.

**Comment by Tschipp** [comment]
Sure, discord is  Tschipp#3159

**Comment by Tschipp** [comment]
I think I have figured out the reason for this. Will try to get a fix out in the next couple of days.
