### ISSUE TITLE
Changing hotkeys crashes the whole game.

### ISSUE THREAD

**Issue by frenchiveruti** [Tschipp/PrimitiveCrafting#18]
https://paste.dimdev.org/ladepedere.mccrash

**Comment by frenchiveruti** [comment]
Modpack: Life at the village.

**Comment by Tschipp** [comment]
To what key did you change it?

**Comment by frenchiveruti** [comment]
Good question, I changed the keybinding to the key that has "<>" on an spanish keyboard layout.  
According to https://keycode.info/ it's key "number 60" aka "IntlBackslash"
Hope it's of any help.

**Comment by Tschipp** [comment]
could you send me your options.txt?

**Comment by frenchiveruti** [comment]
Hi @Tschipp I can try to recreate the error but of course I deleted your mod as soon as it gave me the crash.

**Comment by frenchiveruti** [comment]
You'll have to give me a moment for it.

**Comment by frenchiveruti** [comment]
https://paste.dimdev.org/evoyavixir.mccrash
Another crash
Would you like my world file?

**Comment by frenchiveruti** [comment]
Here's my MultiMC instance with all the mods I'm using, just try to craft something and it should crash.

https://drive.google.com/open?id=1xmYRCKaFWO9kZP-VuuYbx2QPVJ79aXzJ

**Comment by Tschipp** [comment]
`key_key.primitive.cyclerecipes.desc:-100`

this is your configuration of the cycle key. I don't really know how that got there.

**Comment by frenchiveruti** [comment]
Me neither tbh, what should I do?
I think even the default config for the mod gives a crash.

**Comment by Tschipp** [comment]
No way, default controls work fine. I think I've narrowed it down and will have a fix ready. Keep in mind though that minecraft keybinds can be finnicky, so it might not register the key if it's some strange special key. Normal letter keys are always best.

**Comment by Tschipp** [comment]
Update out now

**Comment by frenchiveruti** [comment]
Thanks, I understand.

**Comment by frenchiveruti** [comment]
Hi there, just tested it, and works, or at least doesn't crash :D
