### ISSUE TITLE
Suggestion: Change Crafttweaker methods to have output as first argument

### ISSUE THREAD

**Issue by Mike-U5** [Tschipp/PrimitiveCrafting#2]
Your zenscript functions go like this:
mods.primitivecrafting.addRecipe(INPUT1, INPUT2, OUTPUT);

However, this is kind of confusing as every single zenscript function in Crafttweaker, Modtweaker and all Tweaker addons that I know of always have item output as **first** argument. Same for recipe removal.
So maybe change it to be like this:
mods.primitivecrafting.addRecipe(OUTPUT, INPUT1, INPUT2);

I'd be good to do this now, since not too many people have written big script files for this mod right now. (But I suspect they will soon since this mod is great.)

If there's a technical reason why you implemented the methods like this then feel free to close this issue and ignore it.

**Comment by Tschipp** [comment]
Hmm, alright I will do that, didn't know about that
