### ISSUE TITLE
FML complains about signature

### ISSUE THREAD

**Issue by frenchiveruti** [Tschipp/PrimitiveCrafting#20]
`[19:22:21] [Client thread/ERROR] [FML]: The mod primitivecrafting is expecting signature 55e88f24d04398481ae6f1ce76f65fd776f14227 for source PrimitiveCrafting-1.12.2-1.4.1.jar, however there is no signature matching that description  `
Just wanted to let you know.

**Comment by Tschipp** [comment]
Yes, haven't gotten around to fix it, just ignore it

**Comment by Tschipp** [comment]
Should no longer be an issue on latest versions
