### ISSUE TITLE
[1.12] Nothing's working.

### ISSUE THREAD

**Issue by MagmaSlime123** [Tschipp/PrimitiveCrafting#25]
Not sure if you support 1.12 or not but none of this mod's features are working.
Holding space, left shift, left menu & left/right-clicking while hovering over items, doesn't do anything, as if this isn't even installed.

Also, what format do we use to specify items in the whitelist/blacklist.

**Comment by Tschipp** [comment]
This is extremely unspecific

**Comment by MagmaSlime123** [comment]
Read the issue.

Holding space, left shift, left menu & left/right-clicking (Default keybinds upon install) while hovering over items, doesn't do anything.

**Comment by Tschipp** [comment]
Still, I'm gonna need logs, videos, folder structures, anything.

**Comment by MagmaSlime123** [comment]
Logs contain nothing.

Apparently I'm a complete dumbass.
