### ISSUE TITLE
incompatible with anyDamage() and transformDamage() ?

### ISSUE THREAD

**Issue by Bluberry-Kat** [Tschipp/PrimitiveCrafting#3]
I have a script that turns a log into 2 planks using an axe. This damages the axe by 1 point.
When this is a regular shapeless recipe, it works as intended.
When it is a primitive crafting recipe, it does one of two things.
1) With a wooden axe with full durability, completes the recipe, but consumes the axe
2) With a wooden axe that has taken damage, does nothing at all.

[Here are the scripts in question.](https://gist.github.com/Birgliss/ac31cdd7a586d654f541b8b2b1054bfe)

I am using v1.1 of Primitive Crafting, and 2758 of forge.

**Comment by Tschipp** [comment]
Interesting... I'm gonna look into that

**Comment by Tschipp** [comment]
I've been able to fix the issue and will have a build ready tomorrow

**Comment by Bluberry-Kat** [comment]
awesome! glad to hear it.
