### ISSUE TITLE
Gray Texture Bug?

### ISSUE THREAD

**Issue by llchris** [Tschipp/PrimitiveCrafting#4]
Original Texture:
![locked](https://user-images.githubusercontent.com/44293974/47218594-9906de80-d3ac-11e8-820b-144bb6c278e3.png)
In-Game Texture:
![2018-10-19_14 37 42](https://user-images.githubusercontent.com/44293974/47218629-b471e980-d3ac-11e8-8509-4508fbe064ee.png)

**Comment by Tschipp** [comment]
Fixed in next release (tomorrow probably)
