### ISSUE TITLE
Crafting doesn't work

### ISSUE THREAD

**Issue by Ravin890** [Tschipp/PrimitiveCrafting#8]
I was testing primitive crafting on version 1.3 on forge 14.23.5.2768 and was unable to craft anything, downgrading mod to version 1.2 the ability to craft items was possible. So you might have disabled the ability to craft with the mod when you updated. (referring to crafting via this mod and not 2x2 crafting grid)

**Comment by Tschipp** [comment]
Yikes. I didn't notice that becasue I always tested it in combination with RecipeStages, and then it works. Will have a fix soon

**Comment by Tschipp** [comment]
An update is out

**Comment by majijn** [comment]
update was uploaded as a minecraft 1.13 mod, is this correct?

**Comment by Tschipp** [comment]
oops my bad
