### ISSUE TITLE
Crafting Integrated Dynamics facades with blocks makes the blocks disappear.

### ISSUE THREAD

**Issue by Pival81** [Tschipp/PrimitiveCrafting#9]
When I craft an Integrated Dynamics' facade with any block, it makes the block disappear, but the facade remains.

**Comment by Tschipp** [comment]
Yeah, PrimitiveCrafting can't really do these special dynamic recipes. I suggest that you blacklist the recipe until I find a solution by adding "integrateddynamics:facade_0" to the blacklist.
